import { getObjCClassDeclar } from "marginnote"
import { onClipperEnd, onClipperBindMother, onClipperResetQuestion, onClipperEditTitle } from "./mnutils-entrance"
import {
  handlers,
  lifecycle,
  onAnswerCardPan,
  onAnswerCardResize,
  onAnswerControlPress,
  onAnswerControlRelease,
  onChooseAnswerCandidate,
  onAnswerToolbarClick,
  onAnswerToolbarSingleTap,
  onAnswerToolbarLongPress,
  onReviewModeIndex,
  onReviewModePrevious,
  onReviewModeNext,
  onReviewModeInfo,
  onReviewModeExit,
  onReviewModeControlPress,
  onReviewModeControlRelease,
  onReviewModeControlHover,
  onMistakeToolbarClick,
  onMistakeLevel0Click,
  onMistakeLevel1Click,
  onMistakeLevel2Click,
  ensureMnutilsEntrance,
  onMnutilsEntranceClick,
  onMnutilsEntranceLongPress,
  onMnutilsEntrancePan,
  onMnutilsQuickMenuDismiss,
  onMnutilsQuickMenuWindowTap,
  onMnutilsQuickMenuOpenPanel,
  onMnutilsQuickMenuFilter,
  onMnutilsQuickMenuSelectAll,
  onMnutilsQuickMenuToggleQuestion,
  onMnutilsQuickMenuToggleBranch,
  onMnutilsQuickMenuStart,
  onMnutilsQuickMenuModePress,
  onMistakeLinkToolbarClick,
  onCloseAnswerCard,
  onLocateAnswerCard,
  onRefreshAnswerCard,
  onPanelCloseButtonSideChanged,
  openMenu,
  queryAddonCommandStatus
} from "./plugin"

const Extension = JSB.defineClass(
  getObjCClassDeclar("答案匹配", "JSExtension"),
  {
    ...lifecycle.instanceMethods,
    ...handlers,
    onClipperEnd, onClipperBindMother, onClipperResetQuestion, onClipperEditTitle,
    queryAddonCommandStatus,
    onAnswerToolbarClick,
    onAnswerToolbarSingleTap,
    onAnswerToolbarLongPress,
    onReviewModeIndex,
    onReviewModePrevious,
    onReviewModeNext,
    onReviewModeInfo,
    onReviewModeExit,
    onReviewModeControlPress,
    onReviewModeControlRelease,
    onReviewModeControlHover,
    onChooseAnswerCandidate,
    onMistakeToolbarClick,
    onMistakeLevel0Click,
    onMistakeLevel1Click,
    onMistakeLevel2Click,
    onMistakeLinkToolbarClick,
    onCloseAnswerCard,
    onLocateAnswerCard,
    onRefreshAnswerCard,
    onPanelCloseButtonSideChanged,
    onAnswerCardPan,
    onAnswerCardResize,
    onAnswerControlPress,
    onAnswerControlRelease,
    ensureMnutilsEntrance,
    onMnutilsEntranceClick,
    onMnutilsEntranceLongPress,
    onMnutilsEntrancePan,
    onMnutilsQuickMenuDismiss,
    onMnutilsQuickMenuWindowTap,
    onMnutilsQuickMenuOpenPanel,
    onMnutilsQuickMenuFilter,
    onMnutilsQuickMenuSelectAll,
    onMnutilsQuickMenuToggleQuestion,
    onMnutilsQuickMenuToggleBranch,
    onMnutilsQuickMenuStart,
  onMnutilsQuickMenuModePress,
    openMenu
  },
  lifecycle.classMethods
)

JSB.newAddon = () => Extension
